version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: agradon-demo
      POSTGRES_PASSWORD: agradon
      POSTGRES_USER: agradon
  mongo:
    image: mongo:4.2
    volumes:
      - ./mongo/data:/data/db
    ports:
      - '27017-27019:27017-27019'
