version: '3'
services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: agradon-demo
      POSTGRES_PASSWORD: agradon
      POSTGRES_USER: agradon
