on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 14.19.1
      uses: actions/setup-node@v1
      with:
        node-version: 14.19.1

    - name: npm install, make test-coverage
      working-directory: ./packages/core
      run: |
        npm install
        npm run test

    - name: Coveralls
      working-directory: ./packages/core
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
