# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.19.1
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.1
      - name: Install
        env:
          CI: true
        run: npm install
      - name: Init
        env:
          CI: true
        run: npm run init
      - name: Lint JS
        env:
          CI: true
        run: npm run lint
